### ISSUE TITLE
Odd crash glitch

### ISSUE THREAD

**Issue by dillfrescott** [vaisest/deepfilter-vst#1]
I'm getting a rather peculiar glitch where, tested on both OBS Studio and FL studio, the program running the .vst3 completely freezes/crashes.

No idea whats cauding it but the first thing that comes to mind could be some sort of a memory leak perhaps?

**Comment by vaisest** [comment]
To be clear this project isn't exactly functional.

Deepfilternet is not thread safe which means each thread allocates the model in memory which can definitely be a memory problem as some programs would rapidly initialise the plugin multiple times when I was testing it.

I also have no clue if it works in general. I'm very new to VST

In the meantime it might be better to try and use something like a LADSPA to VST wrapper?

**Comment by jreoka** [comment]
Oh, actually im using the rnn noise vst and its working really well, pretty much the same as deepfilternet. So I'll just use that! Thank you though!

**Comment by jreoka** [comment]
Ill close this for now!
